USE [master]
GO

/****** Object:  Database [ClinicManagementSystemDB]    Script Date: 5/28/2024 5:05:02 PM ******/
CREATE DATABASE [ClinicManagementSystemDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClinicManagementSystemDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ClinicManagementSystemDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ClinicManagementSystemDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ClinicManagementSystemDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ClinicManagementSystemDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClinicManagementSystemDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ClinicManagementSystemDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET  MULTI_USER 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ClinicManagementSystemDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ClinicManagementSystemDB] SET  READ_WRITE 
GO

